#!/usr/bin/env bash

function bootstrap {
  local shome="${_openvpn_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure net/openvpn
}

bootstrap
